### PR TITLE
Stop begging for hand-outs and earn some karma :)

### PR DESCRIPTION
**Pull request by bobf**
We're all grown-up enough to buy our own coffee these days; let's
suggest people spend their money on something more beneficial.

### CODE REVIEW

**Comment by bobf** [comment]
Does merging do anything ? Thought I'd give it a try ... [since we agreed in the mail group that this was fine I think ?]

**Comment by sebastinas** [comment]
Let's ping @ikanobori to get it deployed.

**Comment by ikanobori** [comment]
Ping worked. Site deployed.

**Comment by bobf** [comment]
Thanks, Simon ! It looks much better now.

Do you know where the PayPal link [on the homepage] is stored in git ? I can't find it ... but I think we should remove that as well; sorry I didn't think of this earlier !

@ikanobori

**Comment by ikanobori** [comment]
Don't worry, I removed that one as well. I think it's in the template? I just did it live for now ;)

**Comment by bobf** [comment]
My man.

**Pull request merged**
